#!/bin/bash

echo -e "WISIU Auto-Installer\n"

# Check if wifi.sh exists
if [ ! -f "wifi.sh" ]; then
    echo "wifi.sh not found."
    echo "Downloading fresh copy..."
    git clone https://github.com/tejasprogaming1713/WifiSimu-T tempfolder

    # Copy wifi.sh from repo
    if [ -f "tempfolder/wifi.sh" ]; then
        cp tempfolder/wifi.sh .
    else
        echo "ERROR: wifi.sh not found inside repo."
        rm -rf tempfolder
        exit 1
    fi

    rm -rf tempfolder
fi

# Final script
FILE="wifi.sh"

chmod +x "$FILE"

echo ""
echo "=============================================="
echo "  Auto-Setup Complete!"
echo "  To run WISIU next time, simply type:"
echo ""
echo "      ./run"
echo "=============================================="
echo ""

./"$FILE"
